## LLaVA 7B
InternVL-LLava-7B:
    model_name: InternVL-LLava-7B
    model_dir: /home/work/workspace_bum/Tokenpruning/FastV/models/InternVL-Chat-ViT-6B-Vicuna-7B
    gen_kwargs:
        max_new_tokens: 512
        min_new_tokens: 1
        do_sample: false
        temperature: 0.0
    max_context_len: 4096
    n_tokens_per_image: 576