llava-v1.5-13b:
    model_name: llava-v1.5-13b
    model_dir: /home/work/workspace_bum/Tokenpruning/FastV/models/llava-v1.5-13b
    gen_kwargs:
        max_new_tokens: 512
        min_new_tokens: 1
        do_sample: false
        temperature: 0.0
    max_context_len: 4096
    n_tokens_per_image: 576